# Site settings
title: disf.asia
email: me@disf.asia
description: "test"
baseurl: ""
url: "http://disf.asia"
paginate: 20
paginate_path: ":num"

# Build settings
markdown: kramdown
permalink: :categories/:title

gems: ['jekyll-less']

lessc: /usr/local/bin/lessc

years: ["2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016"]

countries:
  AT:
    name: Austria
  CH:
    name: Switzerland
  CZ:
    name: Czech Republic
  DE:
    name: Germany
  ES:
    name: Spain
  FR:
    name: France
  IT:
    name: Italy
  LA:
    name: Laos
  NL: 
    name: Netherlands
  PT:
    name: Portugal
  UK:
    name: United Kingdom
  US:
    name: United States
  TH:
    name: Thailand
    url: thailand
  VN:
    name: Vietnam
  KH:
    name: Cambodia
