# Site settings
title: disf.asia
email: your-email@domain.com
description: "test"
baseurl: ""
url: "http://disf.asia"
paginate: 20
paginate_path: ":num"

# Build settings
markdown: kramdown
permalink: :categories/:title

gems: ['jekyll-less']

lessc: /usr/local/bin/lessc

countries:
  DE:
    name: Germany