# Site settings
title: disf.asia
email: me@disf.asia
description: "test"
baseurl: ""
url: "http://disf.asia"
paginate: 20
paginate_path: ":num"

# Build settings
markdown: kramdown
permalink: :title

gems: ['jekyll-paginate']

lessc: /usr/local/bin/lessc

years: ["2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016"]

all_countries_number: 196

countries:
  AT:
    name: Austria
    url: austria
    code: AT
  KH:
    name: Cambodia
    url: cambodia
    code: KH
  CZ:
    name: Czech Republic
    url: czech-republic
    code: CZ
  FR:
    name: France
    url: france
    code: FR
  DE:
    name: Germany
    url: germany
    code: DE
  IT:
    name: Italy
    url: italy
    code: IT
  LA:
    name: Laos
    url: laos
    code: LA
  NL: 
    name: Netherlands
    url: netherlands
    code: NL
  PL:
    name: Poland
    url: poland
    code: PL
  PT:
    name: Portugal
    url: portugal
    code: PT
  SK:
    name: Slovakia
    url: slovakia
    code: SK
  ES:
    name: Spain
    url: spain
    code: ES
  CH:
    name: Switzerland
    url: switzerland
    code: CH
  TH:
    name: Thailand
    url: thailand
    code: TH
  GB:
    name: United Kingdom
    url: united-kingdom
    code: GB
  US:
    name: United States
    url: united-states
    code: US
  VN:
    name: Vietnam
    url: vietnam
    code: VN
